version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=bank_db
      - DB_USER=postgres
      - DB_PASSWORD=069151  
    depends_on:
      - db
    volumes:
      - ./app:/app/app
    networks:
      - bank-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=bank_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=069151  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bank-network

volumes:
  postgres_data:

networks:
  bank-network:
    driver: bridge