@baseUrl = http://localhost:5000
@username = admin
@password = admin123

### Login first
# @name login
POST {{baseUrl}}/login
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}

### List All Accounts
GET {{baseUrl}}/bank/list

### Create New Account
POST {{baseUrl}}/bank/create
Content-Type: application/x-www-form-urlencoded

first_name=sami&last_name=serghini&email=sami.ser@gmail.com&phone=+212617652515&address=rue FAR, fes&date_of_birth=1996-06-25&gender=M&job=entrepreneur&type=checking&balance=80000&interest_rate=2.5

### View Account Details
GET {{baseUrl}}/bank/view/601

### Edit Account
POST {{baseUrl}}/bank/edit/544
Content-Type: application/x-www-form-urlencoded

type=savings&balance=90000&status=true&interest_rate=3.0

### Delete Account
POST {{baseUrl}}/bank/delete/100001

### Search Accounts
POST {{baseUrl}}/bank/search
Content-Type: application/x-www-form-urlencoded

search_term=sami