@baseUrl = http://localhost:5000
@username = admin
@password = admin123

### Login first
# @name login
POST {{baseUrl}}/login
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}

### Dashboard Analytics
GET {{baseUrl}}/analytics/dashboard