@baseUrl = http://localhost:5000
@username = admin
@password = admin123

### Login (use this first to get authenticated)
# @name login
POST {{baseUrl}}/login
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}

### Logout
GET {{baseUrl}}/logout