# Bank Operations Tests

### Get Menu
GET http://localhost:5000/bank/menu

### List All Accounts
GET http://localhost:5000/bank/list

### Create New Account
POST http://localhost:5000/bank/create
Content-Type: application/x-www-form-urlencoded

first_name=Jane&last_name=Smith&email=jane@example.com&phone=0987654321&address=456 Elm St&date_of_birth=1985-05-15&gender=F&job=Doctor&type=checking&balance=1500&interest_rate=1.5

### View Account
GET http://localhost:5000/bank/view/1

### Edit Account
POST http://localhost:5000/bank/edit/1
Content-Type: application/x-www-form-urlencoded

type=savings&balance=2000&status=true&interest_rate=3.0

### Delete Account
POST http://localhost:5000/bank/delete/1

### Search Accounts
POST http://localhost:5000/bank/search
Content-Type: application/x-www-form-urlencoded

search_term=John

### Deposit
POST http://localhost:5000/account/1/deposit
Content-Type: application/x-www-form-urlencoded

amount=500&description=Monthly deposit

### Withdraw
POST http://localhost:5000/account/1/withdraw
Content-Type: application/x-www-form-urlencoded

amount=200&description=ATM withdrawal

### Transfer
POST http://localhost:5000/account/1/transfer
Content-Type: application/x-www-form-urlencoded

to_account=2&amount=300&description=Fund transfer

### Bank Statement
POST http://localhost:5000/account/1/statement
Content-Type: application/x-www-form-urlencoded

start_date=2024-01-01&end_date=2024-12-31

### Test Error Page
GET http://localhost:5000/bank/errors/404