@baseUrl = http://localhost:5000
@username = admin
@password = admin123

POST {{baseUrl}}/login
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}

GET {{baseUrl}}/bank/errors/404

GET {{baseUrl}}/bank/errors/500

GET {{baseUrl}}/bank/errors/403

GET {{baseUrl}}/bank/errors/401

POST {{baseUrl}}/login
Content-Type: application/x-www-form-urlencoded

username=wrong&password=wrong